{
  "version": "2.1",
  "executors": {
    "executor": {
      "docker": [
        {
          "image": "circleci/rust:latest"
        }
      ]
    }
  },
  "workflows": {
    "version": 2,
    "all": {
      "jobs": [
        "can build",
        {
          "tests pass": {
            "requires": [
              "can build"
            ]
          }
        },
        {
          "code formatted": {
            "requires": [
              "can build"
            ]
          }
        },
        {
          "dependencies updated": {
            "filters": {
              "branches": {
                "only": [
                  "master"
                ]
              },
            },
            "requires": [
              "can build"
            ]
          }
        },
        {
          "no warnings": {
            "filters": {
              "branches": {
                "only": [
                  "master"
                ]
              },
            },
            "requires": [
              "tests pass"
            ]
          }
        }
      ]
    }
  },
  "jobs": {
    "can build": {
      "executor": "executor",
      "steps": [
        "checkout",
        {
          "restore_cache": {
            "keys": [
              "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}",
              "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}"
            ]
          }
        },
        {
          "run": "cargo build --all"
        },
        {
          "save_cache": {
            "paths": [
              "/usr/local/cargo/registry",
              "target/"
            ],
            "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
          }
        }
      ]
    },
    "tests pass": {
      "executor": "executor",
      "steps": [
        "checkout",
        {
          "restore_cache": {
            "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
          }
        },
        {
          "run": "cargo test --all"
        }
      ]
    },
    "code formatted": {
      "executor": "executor",
      "steps": [
        "checkout",
        {
          "restore_cache": {
            "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
          }
        },
        {
          "run": "rustup component add rustfmt"
        },
        {
          "run": "cargo fmt --all -- --check"
        }
      ]
    },
    "no warnings": {
      "executor": "executor",
      "steps": [
        "checkout",
        {
          "restore_cache": {
            "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
          }
        },
        {
          "run": "RUSTFLAGS=\"--deny warnings\" cargo build --all"
        }
      ]
    },
    "dependencies updated": {
      "executor": "executor",
      "steps": [
        "checkout",
        {
          "restore_cache": {
            "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
          }
        },
        {
          "run": "cargo update --locked"
        }
      ]
    }
  }
}
